[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Explicitly disable Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    disable = true
